---
version: '2.0'

services:

<<<<<<< HEAD
 mongodb:
  
  container_name: mongodb
  
  build:
    context: .
    dockerfile: mongodb.dockerfile
  
  volumes:
      - /AZVOL/mongodb/data:/mongodb/data
      - /mnt/mongodb/log:/mongodb/log

  networks:
     - bridge-conn

 nginx:

  container_name: nginx

  build:
=======
 nginx:

  container_name: nginx
 
  build:  
>>>>>>> b5c21e110cadf3559b8c3f40d97f759a6246b993
   context: .
   dockerfile: nginx.dockerfile

  restart: always

  ports:
     - 80:80

  links:
<<<<<<< HEAD
     - nodejs

  networks:
=======
     - nodejs:nodejs

  networks: 
>>>>>>> b5c21e110cadf3559b8c3f40d97f759a6246b993
     - bridge-conn



 nodejs:

  container_name: nodejs

  tty: true

<<<<<<< HEAD
  build:
=======
  build: 
>>>>>>> b5c21e110cadf3559b8c3f40d97f759a6246b993
   context: .
   dockerfile: node.dockerfile

  volumes:
    - /AZVOL/sailapi:/AZVOL
<<<<<<< HEAD
  
  links:
    - mongodb

  networks:
=======

  networks: 
>>>>>>> b5c21e110cadf3559b8c3f40d97f759a6246b993
     - bridge-conn



networks:
   bridge-conn:
    driver: bridge
<<<<<<< HEAD

=======
>>>>>>> b5c21e110cadf3559b8c3f40d97f759a6246b993
